// api/proto/gogaghe/v1/gogaghe.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gogaghe/v1/gogaghe.proto

package gogaghev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GogagheService_Set_FullMethodName           = "/gogaghe.v1.GogagheService/Set"
	GogagheService_Get_FullMethodName           = "/gogaghe.v1.GogagheService/Get"
	GogagheService_Delete_FullMethodName        = "/gogaghe.v1.GogagheService/Delete"
	GogagheService_SurfaceSearch_FullMethodName = "/gogaghe.v1.GogagheService/SurfaceSearch"
	GogagheService_LexicalSearch_FullMethodName = "/gogaghe.v1.GogagheService/LexicalSearch"
	GogagheService_VectorSearch_FullMethodName  = "/gogaghe.v1.GogagheService/VectorSearch"
	GogagheService_HybridSearch_FullMethodName  = "/gogaghe.v1.GogagheService/HybridSearch"
)

// GogagheServiceClient is the client API for GogagheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GogagheServiceClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Single-strategy dedicated search RPCs:
	SurfaceSearch(ctx context.Context, in *SurfaceSearchRequest, opts ...grpc.CallOption) (*SurfaceSearchResponse, error)
	LexicalSearch(ctx context.Context, in *LexicalSearchRequest, opts ...grpc.CallOption) (*LexicalSearchResponse, error)
	VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
	// Multi-strategy fused hybrid search RPC:
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
}

type gogagheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGogagheServiceClient(cc grpc.ClientConnInterface) GogagheServiceClient {
	return &gogagheServiceClient{cc}
}

func (c *gogagheServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, GogagheService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, GogagheService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, GogagheService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) SurfaceSearch(ctx context.Context, in *SurfaceSearchRequest, opts ...grpc.CallOption) (*SurfaceSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SurfaceSearchResponse)
	err := c.cc.Invoke(ctx, GogagheService_SurfaceSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) LexicalSearch(ctx context.Context, in *LexicalSearchRequest, opts ...grpc.CallOption) (*LexicalSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LexicalSearchResponse)
	err := c.cc.Invoke(ctx, GogagheService_LexicalSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) VectorSearch(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, GogagheService_VectorSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gogagheServiceClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, GogagheService_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GogagheServiceServer is the server API for GogagheService service.
// All implementations should embed UnimplementedGogagheServiceServer
// for forward compatibility.
type GogagheServiceServer interface {
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Single-strategy dedicated search RPCs:
	SurfaceSearch(context.Context, *SurfaceSearchRequest) (*SurfaceSearchResponse, error)
	LexicalSearch(context.Context, *LexicalSearchRequest) (*LexicalSearchResponse, error)
	VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	// Multi-strategy fused hybrid search RPC:
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
}

// UnimplementedGogagheServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGogagheServiceServer struct{}

func (UnimplementedGogagheServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedGogagheServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedGogagheServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedGogagheServiceServer) SurfaceSearch(context.Context, *SurfaceSearchRequest) (*SurfaceSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SurfaceSearch not implemented")
}
func (UnimplementedGogagheServiceServer) LexicalSearch(context.Context, *LexicalSearchRequest) (*LexicalSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LexicalSearch not implemented")
}
func (UnimplementedGogagheServiceServer) VectorSearch(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VectorSearch not implemented")
}
func (UnimplementedGogagheServiceServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedGogagheServiceServer) testEmbeddedByValue() {}

// UnsafeGogagheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GogagheServiceServer will
// result in compilation errors.
type UnsafeGogagheServiceServer interface {
	mustEmbedUnimplementedGogagheServiceServer()
}

func RegisterGogagheServiceServer(s grpc.ServiceRegistrar, srv GogagheServiceServer) {
	// If the following call panics, it indicates UnimplementedGogagheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GogagheService_ServiceDesc, srv)
}

func _GogagheService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_SurfaceSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SurfaceSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).SurfaceSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_SurfaceSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).SurfaceSearch(ctx, req.(*SurfaceSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_LexicalSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LexicalSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).LexicalSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_LexicalSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).LexicalSearch(ctx, req.(*LexicalSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_VectorSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).VectorSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_VectorSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).VectorSearch(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GogagheService_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GogagheServiceServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GogagheService_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GogagheServiceServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GogagheService_ServiceDesc is the grpc.ServiceDesc for GogagheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GogagheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gogaghe.v1.GogagheService",
	HandlerType: (*GogagheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _GogagheService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _GogagheService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _GogagheService_Delete_Handler,
		},
		{
			MethodName: "SurfaceSearch",
			Handler:    _GogagheService_SurfaceSearch_Handler,
		},
		{
			MethodName: "LexicalSearch",
			Handler:    _GogagheService_LexicalSearch_Handler,
		},
		{
			MethodName: "VectorSearch",
			Handler:    _GogagheService_VectorSearch_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _GogagheService_HybridSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gogaghe/v1/gogaghe.proto",
}
