// api/proto/gogaghe/v1/gogaghe.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gogaghe/v1/gogaghe.proto

package gogaghev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchStrategy specifies the matching strategy to use in search queries.
type SearchStrategy int32

const (
	SearchStrategy_SEARCH_STRATEGY_UNSPECIFIED    SearchStrategy = 0 // Automatically enables all strategies matching provided query/vector fields
	SearchStrategy_SEARCH_STRATEGY_SURFACE_NGRAM  SearchStrategy = 1 // Character N-gram (Surface / Typo tolerance / Substring)
	SearchStrategy_SEARCH_STRATEGY_LEXICAL_BM25   SearchStrategy = 2 // Okapi BM25 Inverted Index (Lexical probabilistic keyword)
	SearchStrategy_SEARCH_STRATEGY_LEXICAL_TFIDF  SearchStrategy = 3 // Salton TF-IDF (Lexical term frequency-inverse document frequency)
	SearchStrategy_SEARCH_STRATEGY_SEMANTIC_LSA   SearchStrategy = 4 // Latent Semantic Analysis (Truncated SVD statistical semantics)
	SearchStrategy_SEARCH_STRATEGY_SEMANTIC_DENSE SearchStrategy = 5 // Dense Vector Cosine Similarity (Deep neural embeddings)
)

// Enum value maps for SearchStrategy.
var (
	SearchStrategy_name = map[int32]string{
		0: "SEARCH_STRATEGY_UNSPECIFIED",
		1: "SEARCH_STRATEGY_SURFACE_NGRAM",
		2: "SEARCH_STRATEGY_LEXICAL_BM25",
		3: "SEARCH_STRATEGY_LEXICAL_TFIDF",
		4: "SEARCH_STRATEGY_SEMANTIC_LSA",
		5: "SEARCH_STRATEGY_SEMANTIC_DENSE",
	}
	SearchStrategy_value = map[string]int32{
		"SEARCH_STRATEGY_UNSPECIFIED":    0,
		"SEARCH_STRATEGY_SURFACE_NGRAM":  1,
		"SEARCH_STRATEGY_LEXICAL_BM25":   2,
		"SEARCH_STRATEGY_LEXICAL_TFIDF":  3,
		"SEARCH_STRATEGY_SEMANTIC_LSA":   4,
		"SEARCH_STRATEGY_SEMANTIC_DENSE": 5,
	}
)

func (x SearchStrategy) Enum() *SearchStrategy {
	p := new(SearchStrategy)
	*p = x
	return p
}

func (x SearchStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_gogaghe_v1_gogaghe_proto_enumTypes[0].Descriptor()
}

func (SearchStrategy) Type() protoreflect.EnumType {
	return &file_gogaghe_v1_gogaghe_proto_enumTypes[0]
}

func (x SearchStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchStrategy.Descriptor instead.
func (SearchStrategy) EnumDescriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{0}
}

// --- Set ---
type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs         int64                  `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`             // 0 = no expiry
	CostMs        int64                  `protobuf:"varint,4,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`          // ComputationCostMs for eviction scoring
	Vector        []float32              `protobuf:"fixed32,5,rep,packed,name=vector,proto3" json:"vector,omitempty"`                // optional pre-computed vector
	AutoEmbed     bool                   `protobuf:"varint,6,opt,name=auto_embed,json=autoEmbed,proto3" json:"auto_embed,omitempty"` // trigger async embedding from value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *SetRequest) GetCostMs() int64 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

func (x *SetRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SetRequest) GetAutoEmbed() bool {
	if x != nil {
		return x.AutoEmbed
	}
	return false
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// --- Get ---
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Vector        []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	AccessCount   int64                  `protobuf:"varint,4,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *GetResponse) GetAccessCount() int64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

// --- Delete ---
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// --- SurfaceSearch (Character N-gram) ---
type SurfaceSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurfaceSearchRequest) Reset() {
	*x = SurfaceSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurfaceSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurfaceSearchRequest) ProtoMessage() {}

func (x *SurfaceSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurfaceSearchRequest.ProtoReflect.Descriptor instead.
func (*SurfaceSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{6}
}

func (x *SurfaceSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SurfaceSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SurfaceSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SurfaceSearchResponse) Reset() {
	*x = SurfaceSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SurfaceSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurfaceSearchResponse) ProtoMessage() {}

func (x *SurfaceSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurfaceSearchResponse.ProtoReflect.Descriptor instead.
func (*SurfaceSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{7}
}

func (x *SurfaceSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- Bm25Search (Lexical BM25) ---
type Bm25SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bm25SearchRequest) Reset() {
	*x = Bm25SearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bm25SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bm25SearchRequest) ProtoMessage() {}

func (x *Bm25SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bm25SearchRequest.ProtoReflect.Descriptor instead.
func (*Bm25SearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{8}
}

func (x *Bm25SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Bm25SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type Bm25SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bm25SearchResponse) Reset() {
	*x = Bm25SearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bm25SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bm25SearchResponse) ProtoMessage() {}

func (x *Bm25SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bm25SearchResponse.ProtoReflect.Descriptor instead.
func (*Bm25SearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{9}
}

func (x *Bm25SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- LexicalSearch (Alias for BM25) ---
type LexicalSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexicalSearchRequest) Reset() {
	*x = LexicalSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexicalSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexicalSearchRequest) ProtoMessage() {}

func (x *LexicalSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexicalSearchRequest.ProtoReflect.Descriptor instead.
func (*LexicalSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{10}
}

func (x *LexicalSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LexicalSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type LexicalSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LexicalSearchResponse) Reset() {
	*x = LexicalSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LexicalSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LexicalSearchResponse) ProtoMessage() {}

func (x *LexicalSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LexicalSearchResponse.ProtoReflect.Descriptor instead.
func (*LexicalSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{11}
}

func (x *LexicalSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- TfidfSearch (Lexical TF-IDF) ---
type TfidfSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TfidfSearchRequest) Reset() {
	*x = TfidfSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TfidfSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfidfSearchRequest) ProtoMessage() {}

func (x *TfidfSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfidfSearchRequest.ProtoReflect.Descriptor instead.
func (*TfidfSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{12}
}

func (x *TfidfSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *TfidfSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type TfidfSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TfidfSearchResponse) Reset() {
	*x = TfidfSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TfidfSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TfidfSearchResponse) ProtoMessage() {}

func (x *TfidfSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TfidfSearchResponse.ProtoReflect.Descriptor instead.
func (*TfidfSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{13}
}

func (x *TfidfSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- LsaSearch (Latent Semantic SVD) ---
type LsaSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsaSearchRequest) Reset() {
	*x = LsaSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsaSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsaSearchRequest) ProtoMessage() {}

func (x *LsaSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsaSearchRequest.ProtoReflect.Descriptor instead.
func (*LsaSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{14}
}

func (x *LsaSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LsaSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type LsaSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsaSearchResponse) Reset() {
	*x = LsaSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsaSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsaSearchResponse) ProtoMessage() {}

func (x *LsaSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsaSearchResponse.ProtoReflect.Descriptor instead.
func (*LsaSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{15}
}

func (x *LsaSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- VectorSearch (Dense Vector Cosine) ---
type VectorSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                         // optional: query text to auto-embed if query_vector is omitted
	QueryVector   []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // optional: pre-computed semantic query vector
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{16}
}

func (x *VectorSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *VectorSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *VectorSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{17}
}

func (x *VectorSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- HybridSearch (RRF Fusion) ---
type HybridSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                         // query text for surface/lexical/lsa
	QueryVector   []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // dense semantic query vector
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	RrfK          float32                `protobuf:"fixed32,4,opt,name=rrf_k,json=rrfK,proto3" json:"rrf_k,omitempty"`                                      // RRF constant, default 60.0
	Strategies    []SearchStrategy       `protobuf:"varint,5,rep,packed,name=strategies,proto3,enum=gogaghe.v1.SearchStrategy" json:"strategies,omitempty"` // Optional: specify exact strategies to fuse (if empty, auto-detects from provided fields)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{18}
}

func (x *HybridSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HybridSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *HybridSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *HybridSearchRequest) GetRrfK() float32 {
	if x != nil {
		return x.RrfK
	}
	return 0
}

func (x *HybridSearchRequest) GetStrategies() []SearchStrategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type HybridSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{19}
}

func (x *HybridSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// --- Shared ---
type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_gogaghe_v1_gogaghe_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_gogaghe_v1_gogaghe_proto_rawDescGZIP(), []int{20}
}

func (x *SearchResult) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SearchResult) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_gogaghe_v1_gogaghe_proto protoreflect.FileDescriptor

const file_gogaghe_v1_gogaghe_proto_rawDesc = "" +
	"\n" +
	"\x18gogaghe/v1/gogaghe.proto\x12\n" +
	"gogaghe.v1\"\x9b\x01\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x15\n" +
	"\x06ttl_ms\x18\x03 \x01(\x03R\x05ttlMs\x12\x17\n" +
	"\acost_ms\x18\x04 \x01(\x03R\x06costMs\x12\x16\n" +
	"\x06vector\x18\x05 \x03(\x02R\x06vector\x12\x1d\n" +
	"\n" +
	"auto_embed\x18\x06 \x01(\bR\tautoEmbed\"'\n" +
	"\vSetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"t\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x12!\n" +
	"\faccess_count\x18\x04 \x01(\x03R\vaccessCount\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"A\n" +
	"\x14SurfaceSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"K\n" +
	"\x15SurfaceSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\">\n" +
	"\x11Bm25SearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"H\n" +
	"\x12Bm25SearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"A\n" +
	"\x14LexicalSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"K\n" +
	"\x15LexicalSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"?\n" +
	"\x12TfidfSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"I\n" +
	"\x13TfidfSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"=\n" +
	"\x10LsaSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"G\n" +
	"\x11LsaSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"c\n" +
	"\x13VectorSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"J\n" +
	"\x14VectorSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"\xb4\x01\n" +
	"\x13HybridSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x13\n" +
	"\x05rrf_k\x18\x04 \x01(\x02R\x04rrfK\x12:\n" +
	"\n" +
	"strategies\x18\x05 \x03(\x0e2\x1a.gogaghe.v1.SearchStrategyR\n" +
	"strategies\"J\n" +
	"\x14HybridSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.gogaghe.v1.SearchResultR\aresults\"L\n" +
	"\fSearchResult\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score*\xdf\x01\n" +
	"\x0eSearchStrategy\x12\x1f\n" +
	"\x1bSEARCH_STRATEGY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSEARCH_STRATEGY_SURFACE_NGRAM\x10\x01\x12 \n" +
	"\x1cSEARCH_STRATEGY_LEXICAL_BM25\x10\x02\x12!\n" +
	"\x1dSEARCH_STRATEGY_LEXICAL_TFIDF\x10\x03\x12 \n" +
	"\x1cSEARCH_STRATEGY_SEMANTIC_LSA\x10\x04\x12\"\n" +
	"\x1eSEARCH_STRATEGY_SEMANTIC_DENSE\x10\x052\xfa\x05\n" +
	"\x0eGogagheService\x126\n" +
	"\x03Set\x12\x16.gogaghe.v1.SetRequest\x1a\x17.gogaghe.v1.SetResponse\x126\n" +
	"\x03Get\x12\x16.gogaghe.v1.GetRequest\x1a\x17.gogaghe.v1.GetResponse\x12?\n" +
	"\x06Delete\x12\x19.gogaghe.v1.DeleteRequest\x1a\x1a.gogaghe.v1.DeleteResponse\x12T\n" +
	"\rSurfaceSearch\x12 .gogaghe.v1.SurfaceSearchRequest\x1a!.gogaghe.v1.SurfaceSearchResponse\x12K\n" +
	"\n" +
	"Bm25Search\x12\x1d.gogaghe.v1.Bm25SearchRequest\x1a\x1e.gogaghe.v1.Bm25SearchResponse\x12T\n" +
	"\rLexicalSearch\x12 .gogaghe.v1.LexicalSearchRequest\x1a!.gogaghe.v1.LexicalSearchResponse\x12N\n" +
	"\vTfidfSearch\x12\x1e.gogaghe.v1.TfidfSearchRequest\x1a\x1f.gogaghe.v1.TfidfSearchResponse\x12H\n" +
	"\tLsaSearch\x12\x1c.gogaghe.v1.LsaSearchRequest\x1a\x1d.gogaghe.v1.LsaSearchResponse\x12Q\n" +
	"\fVectorSearch\x12\x1f.gogaghe.v1.VectorSearchRequest\x1a .gogaghe.v1.VectorSearchResponse\x12Q\n" +
	"\fHybridSearch\x12\x1f.gogaghe.v1.HybridSearchRequest\x1a .gogaghe.v1.HybridSearchResponseB5Z3github.com/bayurkp/gogaghe/pkg/gogaghe/v1;gogaghev1b\x06proto3"

var (
	file_gogaghe_v1_gogaghe_proto_rawDescOnce sync.Once
	file_gogaghe_v1_gogaghe_proto_rawDescData []byte
)

func file_gogaghe_v1_gogaghe_proto_rawDescGZIP() []byte {
	file_gogaghe_v1_gogaghe_proto_rawDescOnce.Do(func() {
		file_gogaghe_v1_gogaghe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gogaghe_v1_gogaghe_proto_rawDesc), len(file_gogaghe_v1_gogaghe_proto_rawDesc)))
	})
	return file_gogaghe_v1_gogaghe_proto_rawDescData
}

var file_gogaghe_v1_gogaghe_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gogaghe_v1_gogaghe_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_gogaghe_v1_gogaghe_proto_goTypes = []any{
	(SearchStrategy)(0),           // 0: gogaghe.v1.SearchStrategy
	(*SetRequest)(nil),            // 1: gogaghe.v1.SetRequest
	(*SetResponse)(nil),           // 2: gogaghe.v1.SetResponse
	(*GetRequest)(nil),            // 3: gogaghe.v1.GetRequest
	(*GetResponse)(nil),           // 4: gogaghe.v1.GetResponse
	(*DeleteRequest)(nil),         // 5: gogaghe.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 6: gogaghe.v1.DeleteResponse
	(*SurfaceSearchRequest)(nil),  // 7: gogaghe.v1.SurfaceSearchRequest
	(*SurfaceSearchResponse)(nil), // 8: gogaghe.v1.SurfaceSearchResponse
	(*Bm25SearchRequest)(nil),     // 9: gogaghe.v1.Bm25SearchRequest
	(*Bm25SearchResponse)(nil),    // 10: gogaghe.v1.Bm25SearchResponse
	(*LexicalSearchRequest)(nil),  // 11: gogaghe.v1.LexicalSearchRequest
	(*LexicalSearchResponse)(nil), // 12: gogaghe.v1.LexicalSearchResponse
	(*TfidfSearchRequest)(nil),    // 13: gogaghe.v1.TfidfSearchRequest
	(*TfidfSearchResponse)(nil),   // 14: gogaghe.v1.TfidfSearchResponse
	(*LsaSearchRequest)(nil),      // 15: gogaghe.v1.LsaSearchRequest
	(*LsaSearchResponse)(nil),     // 16: gogaghe.v1.LsaSearchResponse
	(*VectorSearchRequest)(nil),   // 17: gogaghe.v1.VectorSearchRequest
	(*VectorSearchResponse)(nil),  // 18: gogaghe.v1.VectorSearchResponse
	(*HybridSearchRequest)(nil),   // 19: gogaghe.v1.HybridSearchRequest
	(*HybridSearchResponse)(nil),  // 20: gogaghe.v1.HybridSearchResponse
	(*SearchResult)(nil),          // 21: gogaghe.v1.SearchResult
}
var file_gogaghe_v1_gogaghe_proto_depIdxs = []int32{
	21, // 0: gogaghe.v1.SurfaceSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	21, // 1: gogaghe.v1.Bm25SearchResponse.results:type_name -> gogaghe.v1.SearchResult
	21, // 2: gogaghe.v1.LexicalSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	21, // 3: gogaghe.v1.TfidfSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	21, // 4: gogaghe.v1.LsaSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	21, // 5: gogaghe.v1.VectorSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	0,  // 6: gogaghe.v1.HybridSearchRequest.strategies:type_name -> gogaghe.v1.SearchStrategy
	21, // 7: gogaghe.v1.HybridSearchResponse.results:type_name -> gogaghe.v1.SearchResult
	1,  // 8: gogaghe.v1.GogagheService.Set:input_type -> gogaghe.v1.SetRequest
	3,  // 9: gogaghe.v1.GogagheService.Get:input_type -> gogaghe.v1.GetRequest
	5,  // 10: gogaghe.v1.GogagheService.Delete:input_type -> gogaghe.v1.DeleteRequest
	7,  // 11: gogaghe.v1.GogagheService.SurfaceSearch:input_type -> gogaghe.v1.SurfaceSearchRequest
	9,  // 12: gogaghe.v1.GogagheService.Bm25Search:input_type -> gogaghe.v1.Bm25SearchRequest
	11, // 13: gogaghe.v1.GogagheService.LexicalSearch:input_type -> gogaghe.v1.LexicalSearchRequest
	13, // 14: gogaghe.v1.GogagheService.TfidfSearch:input_type -> gogaghe.v1.TfidfSearchRequest
	15, // 15: gogaghe.v1.GogagheService.LsaSearch:input_type -> gogaghe.v1.LsaSearchRequest
	17, // 16: gogaghe.v1.GogagheService.VectorSearch:input_type -> gogaghe.v1.VectorSearchRequest
	19, // 17: gogaghe.v1.GogagheService.HybridSearch:input_type -> gogaghe.v1.HybridSearchRequest
	2,  // 18: gogaghe.v1.GogagheService.Set:output_type -> gogaghe.v1.SetResponse
	4,  // 19: gogaghe.v1.GogagheService.Get:output_type -> gogaghe.v1.GetResponse
	6,  // 20: gogaghe.v1.GogagheService.Delete:output_type -> gogaghe.v1.DeleteResponse
	8,  // 21: gogaghe.v1.GogagheService.SurfaceSearch:output_type -> gogaghe.v1.SurfaceSearchResponse
	10, // 22: gogaghe.v1.GogagheService.Bm25Search:output_type -> gogaghe.v1.Bm25SearchResponse
	12, // 23: gogaghe.v1.GogagheService.LexicalSearch:output_type -> gogaghe.v1.LexicalSearchResponse
	14, // 24: gogaghe.v1.GogagheService.TfidfSearch:output_type -> gogaghe.v1.TfidfSearchResponse
	16, // 25: gogaghe.v1.GogagheService.LsaSearch:output_type -> gogaghe.v1.LsaSearchResponse
	18, // 26: gogaghe.v1.GogagheService.VectorSearch:output_type -> gogaghe.v1.VectorSearchResponse
	20, // 27: gogaghe.v1.GogagheService.HybridSearch:output_type -> gogaghe.v1.HybridSearchResponse
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gogaghe_v1_gogaghe_proto_init() }
func file_gogaghe_v1_gogaghe_proto_init() {
	if File_gogaghe_v1_gogaghe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gogaghe_v1_gogaghe_proto_rawDesc), len(file_gogaghe_v1_gogaghe_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gogaghe_v1_gogaghe_proto_goTypes,
		DependencyIndexes: file_gogaghe_v1_gogaghe_proto_depIdxs,
		EnumInfos:         file_gogaghe_v1_gogaghe_proto_enumTypes,
		MessageInfos:      file_gogaghe_v1_gogaghe_proto_msgTypes,
	}.Build()
	File_gogaghe_v1_gogaghe_proto = out.File
	file_gogaghe_v1_gogaghe_proto_goTypes = nil
	file_gogaghe_v1_gogaghe_proto_depIdxs = nil
}
